// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs1zBJpT3sUAFqe0ZizG17sx2Mt16HslA',
    appId: '1:12369727051:web:74eb2bdccc3405d0d4c7ce',
    messagingSenderId: '12369727051',
    projectId: 'challenge-tsyp-cas-app',
    authDomain: 'challenge-tsyp-cas-app.firebaseapp.com',
    storageBucket: 'challenge-tsyp-cas-app.firebasestorage.app',
    measurementId: 'G-7VD31QW1G7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7YV0xcryBiTpABGCNkm17YV93coF00f8',
    appId: '1:12369727051:android:c3ca577acfc78fcbd4c7ce',
    messagingSenderId: '12369727051',
    projectId: 'challenge-tsyp-cas-app',
    storageBucket: 'challenge-tsyp-cas-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiE7sGbFXbyssRnaScVrNg6x0aF2Z2fuM',
    appId: '1:12369727051:ios:b13da1a7b6219803d4c7ce',
    messagingSenderId: '12369727051',
    projectId: 'challenge-tsyp-cas-app',
    storageBucket: 'challenge-tsyp-cas-app.firebasestorage.app',
    iosBundleId: 'com.example.challengeTsypCasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiE7sGbFXbyssRnaScVrNg6x0aF2Z2fuM',
    appId: '1:12369727051:ios:b13da1a7b6219803d4c7ce',
    messagingSenderId: '12369727051',
    projectId: 'challenge-tsyp-cas-app',
    storageBucket: 'challenge-tsyp-cas-app.firebasestorage.app',
    iosBundleId: 'com.example.challengeTsypCasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs1zBJpT3sUAFqe0ZizG17sx2Mt16HslA',
    appId: '1:12369727051:web:4400a3fd2837532bd4c7ce',
    messagingSenderId: '12369727051',
    projectId: 'challenge-tsyp-cas-app',
    authDomain: 'challenge-tsyp-cas-app.firebaseapp.com',
    storageBucket: 'challenge-tsyp-cas-app.firebasestorage.app',
    measurementId: 'G-CGDHYN8D8X',
  );
}
